copyright: 'This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>. Kx® and kdb+ are registered trademarks of <a href="https://kx.com">Kx Systems, Inc.</a>, a subsidiary of <a href="http://www.firstderivatives.com/">First Derivatives plc</a>.'
dev_addr: '0.0.0.0:8000'
docs_dir: 'docs'
extra_css: 
  - '//code.kx.com/stylesheets/extra.css'
  - stylesheets/extra.css
  - '//code.kx.com/stylesheets/prism.css'
extra_javascript: 
  # See /ref/syntax/#projection to see if MathJax is working 
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://code.jquery.com/jquery-3.1.1.min.js'
  # - '//code.kx.com/scripts/fdtracker.js'
  - 'https://tracker.mrpfd.com/tracker.js'
  - '//code.kx.com/scripts/googleanalytics.js'
  # - 'http://code.kx.com/scripts/theme.js'
  - 'https://use.fontawesome.com/3dbf29ed12.js'
  # - 'scripts/arrive.min.js' # required for theme.js
  # theme.js modifies HTML to prepare for prism.js
  - 'scripts/theme.js'
  # Prism script includes plugin Copy to Clipboard http://prismjs.com/download.html
  # Omits plugins Command Line, Line highlight, and Line Numbers: no effect
  - '//code.kx.com/scripts/prism.js'
  # - 'scripts/prism.js'
markdown_extensions:
  - admonition
  # - codehilite(guess_lang=false)
  - extra
  # - fenced_code
  - fontawesome_markdown
  - pymdownx.arithmatex
  # - pymdownx.betterem(smart_enable=all)
  # - pymdownx.caret
  # - pymdownx.critic
  # - pymdownx.emoji:
  # emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  # - pymdownx.smartsymbols
  # - pymdownx.superfences
  # - pymdownx.tasklist(custom_checkbox=true)
  # - pymdownx.tilde
  - toc(permalink=true)
site_dir: 'site'
site_author: 'Kx Systems'
site_description: Resources for kdb+ programmers
site_favicon: './img/favicon.ico'
# config.site_name: 'code.kx.com'
site_name: 'code.kx.com'
site_url: 'http://code.kx.com'
remote_branch: 'master'
# repo_name: 'GitHub'
# repo_url: 'https://github.com/kxsystems/docs'
theme: 'material'
# theme_dir for favicon
#theme_dir: 'theme'
extra:
  logo: 'img/kx.jpeg'
  palette: 
    primary: 'blue'
    accent: 'deep orange'
  # version: '0.1.0'
pages:
  - Home: index.md
  - Get started: learn.md
  - Reference card: ref/card.md
  - Reference: 
    - Adverbs: ref/adverbs.md
    - Command line: ref/cmdline.md
    - Datatypes: ref/datatypes.md
    - Debugging: ref/debug.md
    - Developer tools: ref/devtools.md
    - Elements: ref/elements.md
    - Errors: ref/error-list.md
    - Glossary: ref/glossary.md
    - IPC protocol: ref/ipc.md
    - Internal functions: ref/internal.md
    - Releases:
      - Changes in 3.5: ref/releases/ChangesIn3.5.md
      - Changes in 3.4: ref/releases/ChangesIn3.4.md
      - Changes in 3.3: ref/releases/ChangesIn3.3.md
      - Changes in 3.2: ref/releases/ChangesIn3.2.md
      - Changes in 3.1: ref/releases/ChangesIn3.1.md
      - Changes in 3.0: ref/releases/ChangesIn3.0.md
      - Changes in 2.8: ref/releases/ChangesIn2.8.md
      - Changes in 2.7: ref/releases/ChangesIn2.7.md
      - Changes in 2.6: ref/releases/ChangesIn2.6.md
      - Changes in 2.5: ref/releases/ChangesIn2.5.md
      - Changes in 2.4: ref/releases/ChangesIn2.4.md
      - Withdrawn: ref/withdrawn.md
    - Semantics:
      - Arithmetic (integer): ref/arith-integer.md
      - Arithmetic (float): ref/arith-float.md
      - Casting & encoding: ref/casting.md
      - Comparison: ref/comparison.md
      - Database: ref/database.md
      - Dictionaries & tables: ref/dictsandtables.md
      - Enumeration: ref/enums.md
      - Environment: ref/environment.md
      - Evaluation control: ref/control.md
      - Error handling: ref/errors.md
      - Files (numbers): ref/filenumbers.md
      - Files (words): ref/filewords.md
      - Functional SQL: ref/funsql.md
      - Joins: ref/joins.md
      - Lists: ref/lists.md
      - Logic: ref/logic.md
      - Markup: ref/doth.md
      - Matrixes: ref/matrixes.md
      - Metadata: ref/metadata.md
      - OS: ref/os.md
      - Parallel processing: ref/peach.md
      - Parse trees: ref/parsetrees.md
      - Q-SQL: ref/qsql.md
          #   - exec: ref/exec.md
      - Randomness: ref/random.md
      - Search: ref/search.md
      - Selection: ref/select.md
      - Sort: ref/sort.md
      - Statistics (aggregates): ref/stats-aggregates.md
      - Statistics (moving): ref/stats-moving.md
      - Strings: ref/strings.md
      - System & callbacks: ref/dotz.md
      - Trigonometry: ref/trig.md
      - Unclassified: ref/unclassified.md
      - Utilities: ref/dotq.md
    - Syntax: ref/syntax.md
    - System commands: ref/syscmds.md
  - Tutorials:
    - Installing: tutorials/install.md
    - Licensing: tutorials/licensing.md
    - A brief introduction:
      - First steps: tutorials/first-steps.md
      - In-memory queries: tutorials/in-memory-queries.md
      - On-disk queries: tutorials/on-disk-queries.md
    - Dictionaries & tables: tutorials/dictsandtables.md
    # - Idioms: tutorials/idioms.md
    - Q by examples: tutorials/q-by-examples.md
    - Shifts & scans: tutorials/shifts-scans.md
    - Starting kdb+:
      - 1. Introduction: tutorials/startingq/introduction.md
      - 2. The q language: tutorials/startingq/language.md
      - 3. IPC: tutorials/startingq/ipc.md
      - 4. Tables: tutorials/startingq/tables.md
      - 5. HDB: tutorials/startingq/hdb.md
      - 6. Kdb+tick: tutorials/startingq/tick.md
    - Views: tutorials/views.md
  - Interface summary: interfaces.md
  - Fusion interfaces:
    - Introduction: interfaces/fusion.md
    - FFI: interfaces/ffi.md
    - Java: interfaces/java-client-for-q.md
    - Kafka: interfaces/kafka.md
    - Python (embedPy): interfaces/embedpy.md
    - Python (PyQ):
      - Quick start: interfaces/pyq/quickstart.md
      - Installation: interfaces/pyq/install.md
      - User guide: interfaces/pyq/user-guide.md
      - Reference: interfaces/pyq/reference.md
      - What’s new: interfaces/pyq/whats-new.md
      - Version history: interfaces/pyq/history.md
    - R: interfaces/with-r.md
  - Other interfaces: 
    - Q client for Bloomberg: interfaces/q-client-for-bloomberg.md
    - C client for kdb+: interfaces/c-client-for-q.md
    - Using C/C++ functions: interfaces/using-c-functions.md
    - C# client for kdb+: interfaces/csharp-client-for-q.md
    - Excel client for kdb+: interfaces/excel-client-for-q.md
    - GPUs: interfaces/gpus.md
    - J client for kdb+: interfaces/j-client-for-q.md
    - Q client for J: interfaces/q-client-for-j.md
    - JDBC client for kdb+: interfaces/jdbc-client-for-kdb.md
    - Matlab client for kdb+: interfaces/matlab-client-for-q.md
    - Kdb+ server for ODBC: interfaces/q-server-for-odbc.md
    - Kdb+ server for ODBC3: interfaces/q-server-for-odbc3.md 
    - Q client for ODBC: interfaces/q-client-for-odbc.md
    - Perl client for kdb+: interfaces/perl-client-for-q.md 
    - Scala client for kdb+: interfaces/scala-client-for-q.md 
  - Cookbook:
    - Introduction: cookbook/introduction.md
    - Alternative in-memory layouts: cookbook/alternative-in-memory-layouts.md
    - Authentication and access: cookbook/authentication.md
    - Bulk Copy Program: cookbook/bcp.md
    - Callbacks: cookbook/callbacks.md
    - Chained tickerplant: cookbook/chained-tickerplant.md
    - Client-server: cookbook/client-server.md
    - Compacting HDB sym: cookbook/compacting-hdb-sym.md
    - Corporate actions: cookbook/corporate-actions.md
    - CPU affinity: cookbook/cpu-affinity.md
    - Custom web server: cookbook/custom-web.md
    - Daemon: cookbook/daemon.md
    - FAQ: cookbook/faq.md
    - FAQ from k4 listbox: cookbook/faq-listbox.md
    - File compression: cookbook/file-compression.md
    - Firewalling: cookbook/firewalling.md
    - Geospatial: cookbook/geospatial.md
    - inetd/xinetd: cookbook/inetd.md
    - Interprocess communication: cookbook/ipc.md
    - Kdb+tick configuration: cookbook/kdb-tick.md
    - Linear programming: cookbook/lp.md
    - Linking columns: cookbook/linking-columns.md
    - Linux production notes: cookbook/linux-production.md
    - Load balancing: cookbook/load-balancing.md
    - Loading from large files: cookbook/loading-from-large-files.md
    - Logging: cookbook/logging.md
    - Multithreaded input: cookbook/multithreaded-input.md
    - Named pipes: cookbook/named-pipes.md
    - ODBC: cookbook/odbc.md
    - Performance tips: cookbook/performance-tips.md
    - Precision: cookbook/precision.md
    - Pivoting tables: cookbook/pivoting-tables.md
    - Programming examples: cookbook/programming-examples.md
    - Programming idioms: cookbook/programming-idioms.md
    - Publish and subscribe: cookbook/publish-subscribe.md
    - Regular expressions: cookbook/regex.md
    - Server calling client: cookbook/server-calling-client.md
    - Splayed schema change: cookbook/splayed-schema-change.md
    - Splayed tables: cookbook/splayed-tables.md
    - Splaying large files: cookbook/splaying-large-files.md
    - SSL/TLS: cookbook/ssl.md
    - Temporal data: cookbook/temporal-data.md
    - Timezones: cookbook/timezones.md
    - Unicode: cookbook/unicode.md
    - Unit tests: cookbook/unit-tests.md
    - Using .z: cookbook/using-dotz.md
    - Write-only RDB: cookbook/w-q.md
    - WebSockets: cookbook/websockets.md
    - Windows Service: cookbook/windows-service.md
  - Platform for Kx: platform.md
  - White papers: whitepapers.md
  - GitHub: github.md
  - Q for Mortals 3: q4m3.md
  - Support: support.md
  - Archive: archive.md
  - About: 
    - Kx technology: about/kxtechnology.md
    - Site news: about/site-news.md
    - This site: about/thissite.md
